team:
  name: "Team"
  base:
    location: "on the deep playa side of the Temple"
battle:
  cry: "HOLD SPACE"
flag:
  color: silver
  highlight: SeaGreen
font:
  family: Copperplate
other_site:
  url: http://ritualwarfare.men
